name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Update to your main branch or the branch you want to deploy from
  workflow_dispatch:  # Allows manual triggers from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows the Action to push changes

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version your project requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      # Ensure this matches your project's build command
      - name: Build project
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
